domain:
  Lx: 1.0 # Length in x-direction (meters)
  Ly: 1.0 # Length in y-direction (meters)
  Nx: 100 # Number of grid points in x
  Ny: 100 # Number of grid points in y

physics:
  viscosity: 0.01 # Kinematic viscosity (m^2/s)
  density: 1.0 # Fluid density (kg/m^3)

solver:
  dt: 0.001 # Time step (seconds)
  n_steps: 100 # Number of time steps
  convergence_tol: 1e-5
